server:
  port: 8893
spring:
  application:
    name: stock
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/group1?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
seata:
  application-id: stock
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
#  data-source-proxy-mode: XA
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      group: "SEATA_GROUP"
#      namespace: "4ff3d755-5519-48fe-845e-618ccd25d0e3"
#      username: "nacos"
#      password: "nacos"